
name = "miyagi-canvas-sync"
main = "worker/worker.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[assets]
not_found_handling = "single-page-application"
directory = "./dist/client"

[observability]
enabled = true

# Environment variables - Development
[vars]
MIYAGI_API_URL = "http://localhost:3001"

# Production environment
[env.production]
name = "miyagi-canvas-sync-prod"

[env.production.vars]
MIYAGI_API_URL = "https://miyagi.chat"

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" },
]

# Durable objects require migrations to create/modify/delete them
[[migrations]]
tag = "v1"
new_sqlite_classes = ["TldrawDurableObject"]

# We store rooms and asset uploads in an R2 bucket
[[r2_buckets]]
binding = 'TLDRAW_BUCKET'
bucket_name = 'miyagi-canvas-content'
preview_bucket_name = 'miyagi-canvas-content-preview'
